### ISSUE TITLE
Try to enable SharedArrayBuffers

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/sync-message#3]
Currently, Papyros performs one extra action when using service-workers, preventing this library from fully meeting the use case. If requests go to a certain domain (i.e. the main domain of the application), we add headers to try to enable SharedArrayBuffers anyway by adding the required headers. This allows running SharedArrayBuffers on servers that cannot be modified, such as GitHub pages. Do you think this would be useful to add to this library, by adding extra options to the ServiceWorker-channel? 
Currently, this is implemented as follows [here](https://github.com/dodona-edu/papyros/blob/main/src/workers/input/InputWorker.ts)

**Comment by alexmojaki** [comment]
The pain point of the service worker is getting it working in the first place. But if it's running and successfully intercepting requests (i.e. is able to add those headers) then the service worker channel should be working fine. In fact I think a working service worker channel may even be better than an atomics channel. So I don't think this would be a useful feature for this library.

So at the moment, I think the service worker adding headers is redundant in Papyros. But I don't think it should be removed because at some point I'd like to add (via a library) interrupting via SharedArrayBuffer.

**Comment by winniederidder** [comment]
The service worker channel would be working fine, but isn't it also slower/less efficient than using SharedArrayBuffers instead? Why do you think the service worker channel works better? It's currently not redundant in Papyros, as current deployment happens on GitHub pages where I like being able to try out the SharedArrayBuffers as well.
What do you mean with interrupting via SharedArrayBuffer? Are you going to combine service worker requests with a SharedArrayBuffer to interrupt those requests, or what exactly is the plan?

**Comment by alexmojaki** [comment]
> isn't it also slower/less efficient than using SharedArrayBuffers instead?

Your previous implementation in Papyros using polling was slower, but with sync-message it should be instant. Have you noticed any difference in performance between the two channels?

> Why do you think the service worker channel works better?

In practice, for futurecoder and Papyros, I don't think it matters. But the atomics channel can only be used by one reader/writer at a time. It also has to allocate a fixed buffer size which messages can't exceed, though I hope to fix that eventually.

> as current deployment happens on GitHub pages where I like being able to try out the SharedArrayBuffers as well

What do you mean by "try out the SharedArrayBuffers"?

> What do you mean with interrupting via SharedArrayBuffer?

Interrupting Python execution without having to terminate the worker.

https://pyodide.org/en/stable/usage/keyboard-interrupts.html

> Are you going to combine service worker requests with a SharedArrayBuffer to interrupt those requests

No. Separate from the pyodide stuff above, the next layer of libraries adds a way to interrupt reading a message. It doesn't depend on the type of channel, and there's no need to combine anything.

**Comment by winniederidder** [comment]
With trying out SharedArrayBuffers, I mean that I test the application in production mode using SharedArrayBuffers. This is done on papyros.dodona.be, hosted by GitHub pages without the required headers for SharedArrayBuffers. Since these headers cannot be modified at the moment, the service worker can add these to allow SharedArrayBuffers to work anyway (potentially only after a page reload, depending on the configuration).
