### ISSUE TITLE
Explicit URL testing

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/sync-message#5]
In regards to this [comment](https://github.com/dodona-edu/dodona/pull/3453#pullrequestreview-943947814), it might be useful export the URL test explicitly so that users can distinguish which requests get passed around (and possibly modified) by the service worker. This would make the package safer to use in case things get changed later.

**Comment by alexmojaki** [comment]
So would you like a function with the same signature as `syncMessageListener` but without actually intercepting the request? So it'll just return `true` to tell you that it *would* intercept it if asked?

**Comment by winniederidder** [comment]
That's what I had in mind, yes.

**Comment by alexmojaki** [comment]
OK, you'll need to make a PR.

Maybe instead of a separate function, a boolean argument like `dryRun` or something on the listener would be better.

**Comment by winniederidder** [comment]
PR is ready, so toss me a collaboration invite so it can be run properly.
Could you elaborate more on what your dryRun argument would entail? At this point I just created a function and I call that internally too (so simply a wrapper around url.includes(suffix))
